params:  
  seed: 8
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd
  
  load_checkpoint: False

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [64,128,64] #[256,128,64]
      d2rl: False
      activation: elu
      initializer:
        name: default
        scale: 2
  config:
    env_name: X152b
    env_config:
      num_envs: 4096
      
    name: ppo_X152b
    reward_shaper:
      # min_val: -1
      scale_value: 0.1

    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    ppo: True
    learning_rate: 1e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    save_best_after: 10
    score_to_win: 100000
    grad_norm: 1.5
    entropy_coef: 0
    truncate_grads: True
    e_clip: 0.2
    clip_value: False
    num_actors: 4096 #4096
    horizon_length: 24
    minibatch_size: 16384 #8192
    mini_epochs: 5
    critic_coef: 2
    normalize_input: True
    bounds_loss_coef: 0.0001
    max_epochs: 500 #2000 #10000
    normalize_value: True
    use_diagnostics: True
    value_bootstrap: True
    #weight_decay: 0.0001
    use_smooth_clamp: False

    save_frequency: 100

    player:
      # render: True
      deterministic: True
      games_num: 100000
      use_vecenv: True